version: "3.8"

services:
  agent:
    build: .
    container_name: agent
    ports:
      - "8000:8000"
    environment:
      PSQL_USERNAME: postgres
      PSQL_PASSWORD: admin
      PSQL_HOST: db
      PSQL_PORT: 5432
      PSQL_DATABASE: scrum_agent
      PSQL_SSLMODE: disable
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scrum_agent
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

